name: "Test pipeline"
on:
  pull_request:
    branches:
      - main
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for PR checks
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: "Codacy Static Code Analysis"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 120
      - run: echo Test
