name: "Test pipeline"
on:
  check_run:
    name: "test/name"
    types:
      - completed
  pull_request:
    branches:
      - main
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - run: echo Test
